# Generated by Django 4.0.2 on 2022-02-11 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScrapedItems', '0004_alter_component_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ('-created_at',)},
        ),
    ]
